[package]
name = "rmaxima"
version = "0.1.0"
authors = ["Andrew Palmer <andrew.pa@outlook.com>"]

[dependencies]
runic = { path = "../runic" }
winit = "0.15"
futures = "0.2"
mio = "0.6"
regex = "1.0"
xml-rs = "0.8"
